# Generated by Django 3.0.4 on 2020-03-26 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='event', verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='event',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
    ]
