# Generated by Django 3.0.4 on 2020-03-16 03:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Título')),
                ('author', models.CharField(max_length=200, verbose_name='Autor')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Sinopsis')),
                ('image', models.ImageField(blank=True, null=True, upload_to='libro', verbose_name='Imagen')),
                ('categories', models.CharField(blank=True, max_length=200, null=True, verbose_name='Categorías')),
                ('status', models.CharField(blank=True, max_length=200, null=True, verbose_name='Status')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Fecha de edición')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'libro',
                'verbose_name_plural': 'libros',
                'ordering': ['-created'],
            },
        ),
    ]
